name: flutterstudy4
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.7.1
  path_provider: ^2.1.6
  share_plus: ^13.2.0
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/toeic/logo/study4_new_logo_sm.png
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
